services:
  - type: web
    name: remprodkitchen
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py createsuperuser_render && gunicorn remProdKitchen.remProdKitchen.wsgi:application --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: remProdKitchen.remProdKitchen.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: True
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SUPERUSER_USERNAME
        value: admin
      - key: SUPERUSER_EMAIL
        value: admin@example.com
      - key: SUPERUSER_PASSWORD
        value: admin123456
    healthCheckPath: /health/

  - type: shell
    name: remprodkitchen-shell
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py shell
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: remProdKitchen.remProdKitchen.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: True 