# Generated by Django 5.2.1 on 2025-06-30 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remProd", "0003_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Supported formats: WebP, PNG, JPG, JPEG, GIF, BMP, TIFF (Max 5MB)",
                null=True,
                upload_to="product_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "webp",
                            "png",
                            "jpg",
                            "jpeg",
                            "gif",
                            "bmp",
                            "tiff",
                        ],
                        message="Please upload a valid image file. Supported formats: WebP, PNG, JPG, JPEG, GIF, BMP, TIFF",
                    )
                ],
            ),
        ),
    ]
